server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka #Usar la rama(branch) que estamos usando actualmente en github
          uri: https://github.com/ilap42/mservices
          search-paths: config-data
  application:
    name: config-mservice